package com.conaxgames.libraries.util;

import com.google.common.collect.ImmutableMap;

import java.util.Map;

public class EnchantmentProcessor {

    /*
    Receives commonly used Enchantment aliases and returns its Bukkit Enchantment.
    Example: '/enchant sharpness 1' --> DAMAGE_ALL, level 1
     */
    private static final Map<String,String> enchantmentmap = ImmutableMap.<String,String>builder()
            .put("0", "PROTECTION_ENVIRONMENTAL")
            .put("prot", "PROTECTION_ENVIRONMENTAL")
            .put("protectionenv", "PROTECTION_ENVIRONMENTAL")
            .put("protection", "PROTECTION_ENVIRONMENTAL")
            .put("protection_environmental", "PROTECTION_ENVIRONMENTAL")
            .put("protectionenvironmental", "PROTECTION_ENVIRONMENTAL")
            .put("1", "PROTECTION_FIRE")
            .put("fireprot", "PROTECTION_FIRE")
            .put("fireprotection", "PROTECTION_FIRE")
            .put("fire_protection", "PROTECTION_FIRE")
            .put("fprotection", "PROTECTION_FIRE")
            .put("fprot", "PROTECTION_FIRE")
            .put("protection_fire", "PROTECTION_FIRE")
            .put("protectionfire", "PROTECTION_FIRE")
            .put("2", "PROTECTION_FALL")
            .put("ff", "PROTECTION_FALL")
            .put("ffalling", "PROTECTION_FALL")
            .put("featherfalling", "PROTECTION_FALL")
            .put("feather_falling", "PROTECTION_FALL")
            .put("protection_fall", "PROTECTION_FALL")
            .put("protectionfall", "PROTECTION_FALL")
            .put("3", "PROTECTION_EXPLOSIONS")
            .put("blastprot", "PROTECTION_EXPLOSIONS")
            .put("bprot", "PROTECTION_EXPLOSIONS")
            .put("blastprotection", "PROTECTION_EXPLOSIONS")
            .put("blast_protection", "PROTECTION_EXPLOSIONS")
            .put("protection_explosions", "PROTECTION_EXPLOSIONS")
            .put("protectionexplosions", "PROTECTION_EXPLOSIONS")
            .put("4", "PROTECTION_PROJECTILE")
            .put("projprot", "PROTECTION_PROJECTILE")
            .put("projectileprotection", "PROTECTION_PROJECTILE")
            .put("pprot", "PROTECTION_PROJECTILE")
            .put("projectile_protection", "PROTECTION_PROJECTILE")
            .put("protection_projectile", "PROTECTION_PROJECTILE")
            .put("protectionprojectile", "PROTECTION_PROJECTILE")
            .put("5", "OXYGEN")
            .put("respiration", "OXYGEN")
            .put("res", "OXYGEN")
            .put("oxygen", "OXYGEN")
            .put("6", "WATER_WORKER")
            .put("aa", "WATER_WORKER")
            .put("aquaa", "WATER_WORKER")
            .put("affinity", "WATER_WORKER")
            .put("aquaaffinity", "WATER_WORKER")
            .put("aqua_affinity", "WATER_WORKER")
            .put("waterworker", "WATER_WORKER")
            .put("water_worker", "WATER_WORKER")
            .put("7", "THORNS")
            .put("thorns", "THORNS")
            .put("8", "DEPTH_STRIDER")
            .put("depth ", "DEPTH_STRIDER")
            .put("dstrider", "DEPTH_STRIDER")
            .put("depth_strider", "DEPTH_STRIDER")
            .put("strider", "DEPTH_STRIDER")
            .put("16", "DAMAGE_ALL")
            .put("sharp", "DAMAGE_ALL")
            .put("sharpness", "DAMAGE_ALL")
            .put("damage_all", "DAMAGE_ALL")
            .put("item_damage", "DAMAGE_ALL")
            .put("17", "DAMAGE_UNDEAD")
            .put("smite", "DAMAGE_UNDEAD")
            .put("damage_undead", "DAMAGE_UNDEAD")
            .put("18", "DAMAGE_ARTHROPODS")
            .put("bane", "DAMAGE_ARTHROPODS")
            .put("arthropods", "DAMAGE_ARTHROPODS")
            .put("baneofarthropods", "DAMAGE_ARTHROPODS")
            .put("banearthropods", "DAMAGE_ARTHROPODS")
            .put("damage_arthropods", "DAMAGE_ARTHROPODS")
            .put("damagearthropods", "DAMAGE_ARTHROPODS")
            .put("19", "KNOCKBACK")
            .put("kb", "KNOCKBACK")
            .put("knock", "KNOCKBACK")
            .put("knockback", "KNOCKBACK")
            .put("20", "FIRE_ASPECT")
            .put("fire", "FIRE_ASPECT")
            .put("firea", "FIRE_ASPECT")
            .put("fireaspect", "FIRE_ASPECT")
            .put("fire_aspect", "FIRE_ASPECT")
            .put("21", "LOOT_BONUS_MOBS")
            .put("looting", "LOOT_BONUS_MOBS")
            .put("loot_bonus_mobs", "LOOT_BONUS_MOBS")
            .put("lootbonusmobs", "LOOT_BONUS_MOBS")
            .put("32", "DIG_SPEED")
            .put("eff", "DIG_SPEED")
            .put("efficiency", "DIG_SPEED")
            .put("digspeed", "DIG_SPEED")
            .put("dig_speed", "DIG_SPEED")
            .put("33", "SILK_TOUCH")
            .put("silk", "SILK_TOUCH")
            .put("silktouch", "SILK_TOUCH")
            .put("silk_touch", "SILK_TOUCH")
            .put("34", "DURABILITY")
            .put("dura", "DURABILITY")
            .put("durability", "DURABILITY")
            .put("unbreaking", "DURABILITY")
            .put("ub", "DURABILITY")
            .put("35", "LOOT_BONUS_BLOCKS")
            .put("fortune", "LOOT_BONUS_BLOCKS")
            .put("lootbonusblocks", "LOOT_BONUS_BLOCKS")
            .put("loot_bonus_blocks", "LOOT_BONUS_BLOCKS")
            .put("48", "ARROW_DAMAGE")
            .put("arrowdamage", "ARROW_DAMAGE")
            .put("power", "ARROW_DAMAGE")
            .put("arrow_damage", "ARROW_DAMAGE")
            .put("bow_damage", "ARROW_DAMAGE")
            .put("bowdamage", "ARROW_DAMAGE")
            .put("49", "ARROW_KNOCKBACK")
            .put("punch", "ARROW_KNOCKBACK")
            .put("bowknockback", "ARROW_KNOCKBACK")
            .put("bow_knockback", "ARROW_KNOCKBACK")
            .put("arrowkb", "ARROW_KNOCKBACK")
            .put("arrow_kb", "ARROW_KNOCKBACK")
            .put("arrow_knockback", "ARROW_KNOCKBACK")
            .put("50", "ARROW_FIRE")
            .put("flame", "ARROW_FIRE")
            .put("arrow_fire", "ARROW_FIRE")
            .put("arrowfire", "ARROW_FIRE")
            .put("51", "ARROW_INFINITE")
            .put("infinity", "ARROW_INFINITE")
            .put("inf", "ARROW_INFINITE")
            .put("arrow_infinity", "ARROW_INFINITE")
            .put("arrowinfinity", "ARROW_INFINITE")
            .put("61", "LUCK")
            .put("luck", "LUCK")
            .put("lucksea", "LUCK")
            .put("luck_sea", "LUCK")
            .put("luckofsea", "LUCK")
            .put("luck_of_sea", "LUCK")
            .put("luckofthesea", "LUCK")
            .put("luck_of_the_sea", "LUCK")
            .put("62", "LURE")
            .put("lure", "LURE")
            .put("mending", "MENDING")
            .put("frostwalker", "FROST_WALKER")
            .put("frostwalk", "FROST_WALKER")
            .put("frost", "FROST_WALKER")
            .put("sweeping", "SWEEPING_EDGE")
            .put("sweepingedge", "SWEEPING_EDGE")
            .put("sweepedge", "SWEEPING_EDGE")
            .put("loyalty", "LOYALTY")
            .put("loyal", "LOYALTY")
            .put("impailing", "IMPALING")
            .put("impale", "IMPALING")
            .put("riptide", "RIPTIDE")
            .put("rip", "RIPTIDE")
            .put("channeling", "CHANNELING")
            .put("channel", "CHANNELING")
            .put("multishot", "MULTISHOT")
            .put("quickcharge", "QUICK_CHARGE")
            .put("qcharge", "QUICK_CHARGE")
            .put("fastcharge", "QUICK_CHARGE")
            .put("piercing", "PIERCING")
            .put("soulspeed", "SOUL_SPEED")
            .put("soilspeed", "SOUL_SPEED")
            .put("swiftsneak", "SWIFT_SNEAK")
            .put("fastsneak", "SWIFT_SNEAK")
            .put("bindingcurse", "BINDING_CURSE")
            .put("curseofbinding", "BINDING_CURSE")
            .put("binding", "BINDING_CURSE")
            .put("curseofvanishing", "VANISHING_CURSE")
            .put("vanishing", "VANISHING_CURSE")
            .put("vanish", "VANISHING_CURSE")
            .build();

    public static String process(String enchantment) {
        String result;
        String key = enchantment;
        result = enchantmentmap.get(key.toLowerCase());
        return result;
    }
}
