name: Uploader and Publisher

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - run: mvn --batch-mode --update-snapshots verify
      - uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          generate_release_notes: true
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
