name: Uploader and Publisher

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'pom.xml'
          find: '<version>dev</version>'
          replace: '<version>${{ github.ref_name }}</version>'
      - run: mvn --batch-mode --update-snapshots verify deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          generate_release_notes: true
